apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  selector:
    matchLabels:
      app: quotes
  replicas: 2
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes
          image: kaviya1996/welcome
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
#              liveness probe will be failing with 8081. just for testing
#              port: 8081
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            failureThreshold: 8